### ISSUE TITLE
Could you disable PostSharp from repository?

### ISSUE THREAD

**Issue by stanislavromanov** [keyboardDrummer/SmartReactives#2]
Anyone who does not have PostSharp installed cannot build the project.
![1](https://cloud.githubusercontent.com/assets/4534725/15627824/bea91d1e-24f0-11e6-8e0c-4a0412b2d23b.PNG)

**Comment by keyboardDrummer** [comment]
Hi Stan,

I've made sure to separate all the functionality that requires PostSharp into separate projects. I guess if you build all the projects in the solution and you don't have PostSharp, then you get this error. However the non-PostSharp projects can be build fine without you having PostSharp, and they provide the core of the SmartReactives functionality. Would you prefer it if I have two solutions, one with and one without the PostSharp projects?

Regards,
Remy.

**Comment by keyboardDrummer** [comment]
Since you haven't replied I'm closing this issue. However I've added a second solution without the PostSharp projects. Also there is now an open source license embedded in the PostSharp projects so anyone will be able to build them.
