### ISSUE TITLE
i use net framework 4.5.2, so error when install package

### ISSUE THREAD

**Issue by lyquocnam** [keyboardDrummer/SmartReactives#6]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'SmartReactives 2.3.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

please help !

**Comment by keyboardDrummer** [comment]
Hi there,

Thank you for your e-mail. I've uploaded a new NuGet package. If you use
the new one I think your problem will be solved.
What I've done is downgrade the project to .NET version 4.5.2 from 4.6.1,
so it will be compatible with more .NET versions.

Regards,
Remy.

**Comment by keyboardDrummer** [comment]
I've done downgraded the project from .NET 4.6.1 to .NET 4.0. I believe this will resolve your issue.

**Comment by lyquocnam** [comment]
this good news, but i updraded from 4.5 to 4.6 too :v:
